        <tr>
          <td colspan="2" bgcolor="#6633FF"><a href="../bms/default.asp"><img src="../images/horbtn_bmup.gif" width="120" height="18" border="0" alt="BookmarkSync"></a><img src="../images/horbtn_colldn.gif" width="145" height="18" alt=""><a href="../news/default.asp"><img src="../images/horbtn_newsup.gif" width="124" height="18" border="0" alt="QuickSync News"></a><a href="../express/default.asp"><img border="0" src="../images/horbtn_exup.gif" width="112" height="18" alt="SyncIT Express"></a></td>
          <td rowspan="2" width="10" valign="top"><img src="../images/rightbar.gif" width="10" height="55" alt=""></td>
        </tr>
        <tr>
          <td colspan="2" width="501" height="37" bgcolor="#000066"><img src="../images/heading.gif" width="501" height="37" alt="MySync Collections"></td>
        </tr>
        <tr>
