        <tr>
          <td colspan="2" width="503" height="23" valign="bottom"><img src="../images/tpix.gif" height="5" width="503" alt=""><br>
            <a href="../bms/"><img src="../images/horbtn_bmup.gif" width="120" height="18" border="0" alt="BookmarkSync"></a><a href="../collections/"><img src="../images/horbtn_collup.gif" width="147" height="18" border="0" alt="MySync Collections"></a><a href="../news/"><img src="../images/horbtn_newsup.gif" border=0 width="124" height="18" alt="QuickSync News"></a><img src="../images/horbtn_exdn.gif" width="112" height="18" alt=""></td>
          <td rowspan="2" width="10" valign="top"><img src="../images/tpix.gif" width="10" height="5" alt=""><img src="../images/rightbar.gif" width="10" height="55" alt=""></td>
        </tr>
        <tr>
          <td colspan="2" width="503" height="37" bgcolor="#000066"><img src="../images/heading_express.gif" width="503" height="37" alt="SyncIT Express"></td>
        </tr>
