        <tr>
          <td colspan="2" background="../images/newsbgfix.gif" width="503" height="23" valign="bottom"><img src="../images/tpix.gif" height="5" width="503" alt=""><br>
            <a href="../bms/"><img src="../images/horbtn_bmup.gif" width="120" height="18" border="0" alt="BookmarkSync"></a><a href="../collections/" alt="BookmarkSync"><img src="../images/horbtn_collup.gif" width="147" height="18" border="0" alt="MySync Collections"></a><img src="../images/horbtn_newsdn.gif" width="124" height="18" alt=""><a href="../express/"><img border="0" src="../images/horbtn_exup.gif" width="112" height="18" alt="SyncIT Express"></a></td>
          <td rowspan="2" width="10" valign="top"><img src="../images/tpix.gif" width="10" height="5" alt=""><img src="../images/rightbar.gif" width="10" height="55" alt=""></td>
        </tr>
        <tr>
          <td colspan="2" width="503" height="37" bgcolor="#000066"><img src="../images/heading_news.gif" width="503" height="37" alt="QuickSync News"></td>
        </tr>
